name: Update Toolchain

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-toolchain:
    name: update toolchain
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: install jq
        uses: dcarbone/install-jq-action@v3

      - name: install lean
        uses: leanprover/lean-action@v1
        with:
          auto-config: false

      - name: get toolchain tags
        id: toolchain-tag
        run: |
          REPO_TAG=$(sed 's/.*://1' lean-toolchain | tr -d '\n')
          LEAN_TAG=$(curl -s "https://api.github.com/repos/leanprover/lean4/releases" | jq -r '.[0].tag_name' | tr -d '\n')
          BATT_TAG=$(curl -s "https://api.github.com/repos/leanprover-community/batteries/releases" | jq -r '.[0].tag_name' | tr -d '\n')
          echo "repo_tag=$REPO_TAG" >> $GITHUB_OUTPUT
          echo "lean_tag=$LEAN_TAG" >> $GITHUB_OUTPUT
          echo "batt_tag=$BATT_TAG" >> $GITHUB_OUTPUT

      - name: update toolchain
        id: update
        if: |
          ${{ steps.toolchain-tag.outputs.repo_tag != steps.toolchain-tag.outputs.lean_tag &&
              steps.toolchain-tag.outputs.batt_tag == steps.toolchain-tag.outputs.lean_tag }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git merge -X theirs origin/bump
          echo "leanprover/lean4:${{ steps.toolchain-tag.outputs.lean_tag }}" > lean-toolchain
          lake update --keep-toolchain

      - name: create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.EXP_PR_TOKEN }}
          commit-message: "chore: bump toolchain ${{ steps.toolchain-tag.outputs.lean_tag }}"
          branch: bump-toolchain-${{ steps.toolchain-tag.outputs.lean_tag }}
          delete-branch: true
          title: "chore: bump toolchain ${{ steps.toolchain-tag.outputs.lean_tag }}"
