# Update `lean-toolchain` in `nightly-testing`

name: Update Nightly Testing

on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/8 * * *'

jobs:
  update-nightly-testing:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v6
        with:
          ref: nightly-testing
          token: ${{ secrets.EXP_PR_TOKEN }}

      - name: git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: update lean-toolchain
        id: toolchain
        run: |
          # get toolchain from batteries/nightly-testing
          curl -L -O "https://raw.githubusercontent.com/leanprover-community/batteries/nightly-testing/lean-toolchain"
          echo "name=$(cut -d ':' -f2 lean-toolchain | tr -d '\n')" >> $GITHUB_OUTPUT
          # check if toolchain has been updated
          if git diff --quiet -- "lean-toolchain"; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: install toolchain
        if: steps.toolchain.outputs.changed == 'true'
        uses: leanprover/lean-action@v1
        with:
          auto-config: false # do nothing
          use-github-cache: false # no caching since we don't build

      - name: update dependencies
        if: steps.toolchain.outputs.changed == 'true'
        run: lake update --keep-toolchain batteries

      - name: commit
        if: steps.toolchain.outputs.changed == 'true'
        run: |
          git add lean-toolchain lake-manifest.json
          git commit -m "chore: update toolchain ${{ steps.toolchain.outputs.name }}"
          git push origin nightly-testing
